"""
app/routers/analysis.py
POST /api/v1/analyze endpoint.
"""

from typing import Optional

from fastapi import APIRouter, File, Form, UploadFile, HTTPException
from fastapi.responses import JSONResponse

from app.models.stride import StrideReport, ErrorResponse
from app.services.analysis_service import run_stride_analysis

router = APIRouter()


@router.post(
    "/analyze",
    response_model=StrideReport,
    summary="Analyze architecture diagram with STRIDE",
    description=(
        "Upload an architecture diagram image (PNG/JPG) and receive an automated "
        "STRIDE threat model generated by GPT-4 Vision via Azure OpenAI."
    ),
    responses={
        200: {"description": "Successful STRIDE analysis report"},
        400: {"model": ErrorResponse, "description": "Invalid image file"},
        413: {"model": ErrorResponse, "description": "File too large"},
        502: {"model": ErrorResponse, "description": "Azure OpenAI error"},
    },
)
async def analyze_architecture(
    image: UploadFile = File(
        ...,
        description="Architecture diagram image (PNG, JPG, WebP). Max 10MB."
    ),
    context: Optional[str] = Form(
        default=None,
        description=(
            "Optional context about the application "
            "(e.g. 'E-commerce with OAuth2 and microservices on Azure')"
        ),
        max_length=1000,
    ),
):
    """
    Analyze an architecture diagram and generate a STRIDE threat model.

    - **image**: Architecture diagram (PNG/JPG/WebP, max 10MB)
    - **context**: Optional free-text description to improve analysis accuracy
    """
    report = await run_stride_analysis(file=image, context=context)
    return report
